# Generated by Django 5.0.7 on 2024-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("id_paciente", models.CharField(max_length=50, unique=True)),
                ("edad", models.IntegerField()),
                ("genero", models.CharField(max_length=10)),
                ("direccion", models.CharField(max_length=255)),
                ("celular", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=254)),
                ("diagnostico", models.TextField()),
                ("alergias", models.TextField()),
            ],
        ),
    ]
